#!/usr/bin/env npx tsx
/**
 * ingest-plays.ts — One-shot bulk insert of plays.ndjson into D1.
 *
 * Usage:
 *   npx tsx scripts/ingest-plays.ts           # insert (refuses if table non-empty)
 *   npx tsx scripts/ingest-plays.ts --force    # truncate and re-insert
 *   npx tsx scripts/ingest-plays.ts --local    # use local D1 (wrangler dev)
 *
 * Reads data/plays.ndjson (generated by feather-to-ndjson.py).
 * Batches into SQL files and runs them via `wrangler d1 execute`.
 */

import { readFileSync, writeFileSync, unlinkSync, existsSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";

const DB_NAME = "spotify-agent-db";
const NDJSON_PATH = join(__dirname, "..", "data", "plays.ndjson");
const BATCH_SIZE = 50; // rows per INSERT statement
const STATEMENTS_PER_FILE = 100; // INSERT statements per SQL file execution

const args = process.argv.slice(2);
const force = args.includes("--force");
const local = args.includes("--local");
const localFlag = local ? "--local" : "";

function execD1(sql: string): string {
  const tmpFile = join(__dirname, "..", ".tmp-ingest.sql");
  writeFileSync(tmpFile, sql);
  try {
    const result = execSync(
      `npx wrangler d1 execute ${DB_NAME} --file=${tmpFile} ${localFlag} --json`,
      { encoding: "utf-8", maxBuffer: 50 * 1024 * 1024 },
    );
    return result;
  } finally {
    if (existsSync(tmpFile)) unlinkSync(tmpFile);
  }
}

function escapeSQL(val: string): string {
  return val.replace(/'/g, "''");
}

async function main() {
  console.log("Ingesting plays.ndjson into D1...");

  // Check if table exists and has data
  try {
    const countResult = execD1("SELECT COUNT(*) as cnt FROM plays;");
    const parsed = JSON.parse(countResult);
    const count = parsed?.[0]?.results?.[0]?.cnt ?? 0;
    if (count > 0 && !force) {
      console.error(`Table 'plays' already has ${count} rows. Use --force to truncate and re-insert.`);
      process.exit(1);
    }
    if (count > 0 && force) {
      console.log(`Truncating ${count} existing rows...`);
      execD1("DELETE FROM plays;");
    }
  } catch {
    // Table might not exist yet — create it
    console.log("Creating plays table...");
    const schemaSql = readFileSync(join(__dirname, "..", "src", "db", "schema.sql"), "utf-8");
    // Extract just the plays table creation
    const playsMatch = schemaSql.match(
      /-- LISTENING HISTORY[\s\S]*?(?=-- =====\n-- USER)/,
    );
    if (playsMatch) {
      execD1(playsMatch[0]);
    }
  }

  // Read NDJSON
  if (!existsSync(NDJSON_PATH)) {
    console.error(`File not found: ${NDJSON_PATH}`);
    console.error("Run: python3 scripts/feather-to-ndjson.py");
    process.exit(1);
  }

  const lines = readFileSync(NDJSON_PATH, "utf-8").trim().split("\n");
  console.log(`Read ${lines.length} rows from plays.ndjson`);

  // Build batched INSERT statements
  const columns = [
    "ts", "platform", "ms_played", "conn_country", "track_name",
    "artist_name", "album_name", "spotify_track_uri", "reason_start",
    "reason_end", "shuffle", "offline", "year", "month", "hour",
    "local_hour", "minutes",
  ];

  const allStatements: string[] = [];

  for (let i = 0; i < lines.length; i += BATCH_SIZE) {
    const batch = lines.slice(i, i + BATCH_SIZE);
    const valueClauses = batch.map((line) => {
      const row = JSON.parse(line);
      const vals = columns.map((col) => {
        const v = row[col];
        if (v == null) return "NULL";
        if (typeof v === "number") return String(v);
        return `'${escapeSQL(String(v))}'`;
      });
      return `(${vals.join(",")})`;
    });

    allStatements.push(
      `INSERT INTO plays (${columns.join(",")}) VALUES ${valueClauses.join(",")};`,
    );
  }

  console.log(`Generated ${allStatements.length} INSERT statements`);

  // Execute in batches of SQL files
  let totalInserted = 0;
  for (let i = 0; i < allStatements.length; i += STATEMENTS_PER_FILE) {
    const fileBatch = allStatements.slice(i, i + STATEMENTS_PER_FILE);
    const sql = fileBatch.join("\n");
    execD1(sql);

    totalInserted += fileBatch.length * BATCH_SIZE;
    const pct = Math.min(100, Math.round((totalInserted / lines.length) * 100));
    process.stdout.write(`\r  Progress: ${pct}% (${Math.min(totalInserted, lines.length)}/${lines.length})`);
  }

  console.log("\n\nVerifying row count...");
  const verifyResult = execD1("SELECT COUNT(*) as cnt FROM plays;");
  const verifyParsed = JSON.parse(verifyResult);
  const finalCount = verifyParsed?.[0]?.results?.[0]?.cnt ?? 0;
  console.log(`  plays table has ${finalCount} rows`);

  if (finalCount !== lines.length) {
    console.error(`  WARNING: expected ${lines.length}, got ${finalCount}`);
  } else {
    console.log("  Ingest complete!");
  }
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
